# N.Kurz, DVEE, GSI, 16-Aug-2001
# N.Kurz, EE,   GSI,  3-MAR-2009: adopted for linux and dim 

ifdef DIMDIR
DIMANN = DIM $(DIMDIR)
DIMCTRL = -DMBS_DIM
DIMINC = -I$(DIMDIR)/dim
 ifeq ($(GSI_OS),Lynx)
 DIMLIB  = $(DIMDIR)/lib_$(GSI_CPU_PLATFORM)/libdim.a
 endif
 ifeq ($(GSI_OS),Linux)
 DIMLIB  = $(DIMDIR)/lib_$(GSI_CPU_PLATFORM)_$(GSI_OS)_$(GSI_OS_VERSION)_$(GSI_OS_TYPE)/libdim.a
 endif
endif

INC = $(MBSROOT)/inc
ifeq ($(GSI_OS),Lynx)
OBJ     = $(MBSROOT)/obj_$(GSI_CPU_PLATFORM)
LIB     = $(MBSROOT)/lib_$(GSI_CPU_PLATFORM)
endif
ifeq ($(GSI_OS),Linux)
OBJ     = $(MBSROOT)/obj_$(GSI_CPU_PLATFORM)_$(GSI_OS)_$(GSI_OS_VERSION)_$(GSI_OS_TYPE)
LIB     = $(MBSROOT)/lib_$(GSI_CPU_PLATFORM)_$(GSI_OS)_$(GSI_OS_VERSION)_$(GSI_OS_TYPE)
endif

SMILIBS      = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(LIB)/lib_smi.a
CES_RIO_LIB = /usr/src/ces/examples/bma/xvmelib.o -L/lib/ces -lvme -lbma -luio -lbus

SHMQ    = -DLYNX__SMEM
ifeq ($(GSI_OS_VERSION),2.5)
POSIX   =  -mthreads
CFLAGS  = $(POSIX) -DLynx -DGSI_MBS -D$(GSI_CPU_ENDIAN) -D$(GSI_CPU_PLATFORM)
LIBS    = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(DIMLIB) \
          $(LIB)/libedit.a -llynx -lnetinet $(CES_LIB)
endif

ifeq ($(GSI_OS_VERSION),3.0)
POSIX   =  -mthreads
CFLAGS  = $(POSIX) -D_THREADS_POSIX4ad4 -DLynx -DGSI_MBS -D$(GSI_CPU_ENDIAN) -D$(GSI_CPU_PLATFORM) 
LIBS    = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(DIMLIB) \
          $(LIB)/libedit.a -llynx  -lnetinet $(CES_LIB)
endif

ifeq ($(GSI_OS_VERSION),3.1)
POSIX   =  -mthreads
CFLAGS  = $(POSIX) -D_THREADS_POSIX4ad4 -DLynx -DGSI_MBS -D$(GSI_CPU_ENDIAN) -D$(GSI_CPU_PLATFORM) 
LIBS    = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(DIMLIB) \
          $(LIB)/libedit.a -lposix-pre1c -lnetinet $(CES_LIB)
endif

ifeq ($(GSI_OS_VERSION),4.0)
POSIX   =  -mthreads
CFLAGS  = $(POSIX) -D_THREADS_POSIX4ad4 -DLynx -DGSI_MBS -D$(GSI_CPU_ENDIAN) -D$(GSI_CPU_PLATFORM)
LIBS    = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(DIMLIB) \
          $(LIB)/libedit.a -lposix-pre1c
SMILIBS = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(LIB)/lib_smi.a \
          $(LIB)/libedit.a -llynx -lposix-pre1c -lnetinet $(CES_LIB)
endif

ifeq ($(GSI_OS),Linux)
ifeq ($(GSI_OS_VERSION),2.6)
POSIX   =
CFLAGS  = $(POSIX) -DLinux -Dunix -DV40 -DGSI_MBS -D$(GSI_CPU_ENDIAN) -D$(GSI_CPU_PLATFORM)
LIBS    = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(DIMLIB) \
          $(LIB)/libedit.a  $(LIB)/lib_mbs.a -lpthread -lrt
SMILIBS = $(LIB)/lib_mbs.a $(LIB)/lib_tools.a $(LIB)/lib_mbs.a $(LIB)/lib_smi.a \
          $(LIB)/libedit.a  -lnetinet
endif
endif

m_read_meb : $(OBJ)/m_read_meb.o  $(OBJ)/objects f_user.c
	gcc -O2 $(CFLAGS) -o m_read_meb -I$(INC) f_user.c $(OBJ)/m_read_meb.o $(LIBS) $(CES_RIO_LIB)
	strip m_read_meb

clean :
	rm -f core *~ *.bak *.jou m_read_meb 
 
